### ISSUE TITLE
[Bug]: Crash on server / client launch

### ISSUE THREAD

**Issue by Flamaghl** [TheIllusiveC4/VeinMining#108]
### Minecraft Version

1.20.1

### What happened?

Hello,

There was no issue with the mod yesterday and I also made no updates to nothing.
But today my Fabric server + client started to crash everytime I try to launch the game, pointing at spectrelib.

As a precision, i have not directly subscribed to spectrelib, the mod from you that I play is Vein Mining (Fabric/Forge/Quilt) -> when I delete it from server / client, game launches normally
(Spectrelib is not in my mod folder, but put itself in my .fabric\processedMods folder : i guess for veinmining to work)

Below is the error part of the server log (and I attach full logs to this ticket) :

[main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
... 4 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/entrypoint/EntrypointUtils
at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:33) ~[spectrelib-0.13.13+1.20.1-8bd44f426b4b2253.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
... 4 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.entrypoint.EntrypointUtils
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.23.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:33) ~[spectrelib-0.13.13+1.20.1-8bd44f426b4b2253.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.23.jar:?]
at net.fabricmc.loader.impl.la
unch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
... 4 more

[latest_server.log](https://github.com/illusivesoulworks/veinmining/files/12818974/latest_server.log)
[crash-2023-10-05_14.38.37-client.txt](https://github.com/illusivesoulworks/veinmining/files/12818975/crash-2023-10-05_14.38.37-client.txt)
[latest_client.log](https://github.com/illusivesoulworks/veinmining/files/12818976/latest_client.log)

Thanks for help !

### How do you trigger this bug?

1. launch server / game with vein mining installed
2. server cannot launch / game crashes, pointing spectrelib

3. delete vein Mining from server / client
4. server / client launch properly

### Loader

Fabric

### Loader Version

0.14.23

### API Version

Fabric API 0.89.3

### Mod Version

veinmining-fabric-1.2.0+1.20.1

### Relevant Log Outputs

[latest_server.log](https://github.com/illusivesoulworks/veinmining/files/12819014/latest_server.log)
[crash-2023-10-05_14.38.37-client.txt](https://github.com/illusivesoulworks/veinmining/files/12819015/crash-2023-10-05_14.38.37-client.txt)
[latest_client.log](https://github.com/illusivesoulworks/veinmining/files/12819016/latest_client.log)

**Comment by Flamaghl** [comment]
For the precisions, I had created this issue previously today under spectrelib (with exact same content), until i tried without vein mining and the game launched fine so I don't know from which of the 2 the issue comes from :)

**Comment by TheIllusiveC4** [comment]
This is an incompatibility with SpectreLib and Fabric Loader 0.14.23. I'm working on an update, but until then downgrading Fabric Loader should serve as a workaround.

**Comment by Flamaghl** [comment]
Oh K, thx ! Appreciate the mod btw 🥰
