### ISSUE TITLE
[Bug]: Crash on 1.19.2

### ISSUE THREAD

**Issue by Rafcioff15** [TheIllusiveC4/VeinMining#62]
### Minecraft Version

1.19.2

### What happened?

Server and client wont start with new 1.19.2 version vein mining

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge 43.1.25

### Mod Version

Vein mining 1.19.2

### Relevant Log Outputs

Crash Report UUID: d0aa733b-75be-4687-906f-59d946b4070e
	FML: 43.1
	Forge: net.minecraftforge:43.1.16[19:15:39] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Vein Mining (veinmining) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[fmlcore-1.19.2-43.1.16.jar%23259!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.16.jar%23259!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin,re:computing_frames}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.16.jar%23259!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.16.jar%23259!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.16.jar%23259!/:?] {}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.1.16-universal.jar%23263!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23258!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.1.16.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

**Comment by TheIllusiveC4** [comment]
Please show the full crash log.

**Comment by Rafcioff15** [comment]
[crash-2022-09-16_20.15.05-fml.txt](https://github.com/illusivesoulworks/veinmining/files/9590556/crash-2022-09-16_20.15.05-fml.txt)

**Comment by Baggytrousers27** [comment]
Was the conflict with comforts?

Edit: Nvm saw the changelog.
